feat: add FluentValidationExtensions
masastack/MASA.Utils pull request #65
Opened 2022-06-01 06:33 UTC by gavin1ee

add FluentValidationExtensions

2022-06-01 06:36 UTC, doddgu requested changes

2022-06-01 06:36 UTC, doddgu commented on src/Extensions/Masa.Utils.Extensions.FluentValidation/FluentValidationExtensions.cs
> +namespace Masa.Utils.Extensions.FluentValidation;
`Masa.Utils.Extensions.FluentValidation` -> change to IRuleBuilder's namespace.

2022-06-01 06:43 UTC, zhenlei520 commented
@doddgu Would it be better to change the class library name to Masa.Utils.Extensions.Validation.FluentValidation?

2022-06-02 10:37 UTC, doddgu approved these changes
LGTM

2022-06-02 10:37 UTC, merged